  spring:
    application:
        name: admin-api
    profiles:
        active: dev
    thymeleaf:
           prefix: classpath:/templates/
           suffix: .html
           encoding: UTF-8
           content-type: text/html
           mode: HTML5
           #关闭缓存，即时刷新
           cache: true

    mvc:
        throw-exception-if-no-handler-found: true
    resources:
        static-locations: classpath:/templates/,upload

  logging:
      config: classpath:log/logback-spring.xml
  server:
      port: 8082

  #热部署生效
  devtools:
      restart:
        enabled: true
        #设置重启的目录
        additional-paths: src/main/java



  mybatis-plus:
    mapper-locations: classpath:/com/njbandou/web/mapper/*.xml
    #实体扫描，多个package用逗号或者分号分隔
    typeAliasesPackage:  com.njbandou.web.mapper
#    typeEnumsPackage: com.njbandou.web.enums
    global-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: 0
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 1
      #驼峰下划线转换
      db-column-underline: true
      #刷新mapper 调试神器
      refresh-mapper: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置（下面3个配置）
      logic-delete-value: 0
      logic-not-delete-value: 1
      # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
      sql-parser-cache: true
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false










